### ISSUE TITLE
Art der Arbeit

### ISSUE THREAD

**Issue by sphew** [fsi-tue/aai#7]
Themen, die nicht eindeutig zu einem Abschlusstypen ("Art der Arbeit": Bachelor/Master/...) gehören, sollten am besten mit "alle" gekennzeichnet werden können.  So können allgemeine Themen formuliert werden, die dann je nach Student in unterschiedlicher Größe bearbeitet werden.

**Comment by elogy** [comment]
Wir könnten uns mal das hier anschauen: https://pypi.org/project/django-multiselectfield/

Das erlaubt uns für ein Datenbankfeld Checkboxen, wir könnten also auch einfach die Möglichkeit lassen, alle Häkchen anzukreuzen, wenn eine Arbeit generisch formuliert ist.

**Comment by elogy** [comment]
Hab das Multiselect in 0307e69 eingefügt und zusätzlich noch das Choice-Feld "nach Absprache" eingefügt, jetzt kann man also auswählen wie man lustig ist. Sollte hiermit fixed sein ;)
